"""Initial migration

Revision ID: 2cf86d906028
Revises:
Create Date: 2026-02-01 16:01:09.695806

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cf86d906028"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect

    conn = op.get_bind()
    inspector = inspect(conn)

    if "exercises" not in inspector.get_table_names():
        # Fresh database — create the base exercises table.
        # Subsequent migrations will add users FK, notes, archived, sort_order, etc.
        op.create_table(
            "exercises",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
            sa.Column("sets", sa.Integer(), nullable=False),
            sa.Column("reps", sa.Integer(), nullable=False),
            sa.Column("weight", sa.Float(), nullable=True),
            sa.Column("workout_day", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default="A"),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_exercises_name"), "exercises", ["name"], unique=False)
    else:
        # Existing database — add workout_day column and index if missing.
        columns = [col["name"] for col in inspector.get_columns("exercises")]
        if "workout_day" not in columns:
            op.add_column(
                "exercises",
                sa.Column("workout_day", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False, server_default="A"),
            )
        indexes = [idx["name"] for idx in inspector.get_indexes("exercises")]
        if "ix_exercises_name" not in indexes:
            op.create_index(op.f("ix_exercises_name"), "exercises", ["name"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the changes made in upgrade()
    op.drop_index(op.f("ix_exercises_name"), table_name="exercises")
    op.drop_column("exercises", "workout_day")
    # ### end Alembic commands ###
